### PR TITLE
Rocket -> Actix Web

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Comment by jackpot51** [comment]
Did you try running this using `example.toml`?

```
cargo run --release example.toml
```

**Comment by mmstick** [comment]
I have not

**Comment by jackpot51** [comment]
There are some instructions in the readme for setting up the database and configuration file. If you need OFX information for a bank you have an account at, you can use http://www.ofxhome.com/

Just be careful to keep any secret data in `secret.toml` and `secret.db`

**Comment by mmstick** [comment]
@jackpot51 Seems to be working now.

**Comment by jackpot51** [comment]
Thanks, it feels much faster!

**Pull request merged**
